# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres1 # Sets service name
#   labels:
#     app: backuppostgres11 # Labels and Selectors
# spec:
#   ports:
#     - port: 5432 # Sets port to run the postgres application
#   selector:
#     app: backuppostgres